version: "3"

services:
  drupal:
    build: .
    image: hisownspace/custom-drupal
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: postgres:14.2
    volumes:
      - drupal-data:/var/lib/postgresql/data
    env_file:
      - .env
  
volumes:
  drupal-data: